name = "SparseSpectralClustering"
uuid = "eb9e3a3a-00b4-44ab-8c29-5b6c0303b29c"
authors = ["Riley Whebell <75467572+rwhebell@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
